# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'QQVideoListCell' do

# ignore all warnings from all pods
inhibit_all_warnings!

#pod 'ZFPlayer', '~> 2.1.5'
pod 'AFNetworking'
pod 'MJExtension'
pod 'SDWebImage'
pod 'Masonry'

end
